#GET all docs
GET http://localhost:3003/api/blogs

###

#GET all users
GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Outside Hollywood",
  "author": "Isaac Botkin",
  "url": "https://www.outside-hollywood.com/",
  "likes": 900
}

###

POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

# not a string request
# {
#   "username": "jacksparrow",
#   "password": "janklog"
# }

# basic superuser
{
  "username": "root",
  "name": "superuser",
  "password": "FranklinLives"
}

###

DELETE http://localhost:3003/api/users/69fa559096a93a9168c9ce5e HTTP/1.1
Content-Type: application/json